fix: #432 Error when logout in the command-line tool
fonoster/fonoster pull request #435
Opened 2022-11-14 16:04 UTC by xquanluu

#432 Error when logout in the command-line tool

2022-11-14 16:06 UTC, xquanluu commented
I have read the CLA Document and I hereby sign the CLA

2022-11-16 14:38 UTC, efraa commented
@xquanluu Thank you for solving this issue. I'd just recommend removing the `grpc-tools` version changes as it's not related to the issue.

2022-11-17 07:58 UTC, xquanluu commented
Hi @efraa 

I'm quite insterested in fonoster, do you have any other good first issue to me. Thanks a lot.

2022-11-17 13:02 UTC, efraa requested changes
Please remove the `package-lock.json` changes.

2022-11-17 13:02 UTC, efraa commented on package.json
> -    "grpc-tools": "1.11.1",
@xquanluu Thank you for solving this issue. I'd just recommend removing the `grpc-tools` version changes as it's not related to the issue.

2022-11-17 22:34 UTC, psanders commented
> Hi @efraa
> 
> I'm quite insterested in fonoster, do you have any other good first issue to me. Thanks a lot.

For sure! Be in the look out because we will continue to add more.

2022-11-18 07:55 UTC, xquanluu commented on package.json
> -    "grpc-tools": "1.11.1",
yes, I fixed it, did change this version for to be able to build on Apple M1 chip.

For package-lock.json, it's automatically generated by npm run make. and it's keep changing every time, do you have any hint so I can avoid make changes in this file.

2022-11-18 13:51 UTC, psanders reviewed
Looks great.

2022-11-18 13:54 UTC, psanders commented on package.json
> -    "grpc-tools": "1.11.1",
@xquanluu the `npm run make` it's meant to be run once. Most of the time using `run build` works fine.

2022-11-18 13:56 UTC, psanders approved these changes
All set here.

2022-11-18 13:59 UTC, psanders approved these changes
Reviewed.

2022-11-18 13:59 UTC, psanders approved these changes

2022-11-19 13:05 UTC, psanders approved these changes

2022-11-21 16:54 UTC, efraa approved these changes

2022-11-21 17:02 UTC, psanders commented
@xquanluu thanks a lot for the PR. It helps a lot. Keep them coming 💪

2022-11-21 17:02 UTC, merged