Fix/privacy field on ctl
fonoster/fonoster pull request #440
Opened 2022-11-19 14:47 UTC by psanders

## Description

This PR is needed to fix the CTL not sending privacy settings. 

Also:

- [x] Re-enabled test, lint, check-types, and format on pre-commit. 
- [x] Fixed linting warnings
- [x] Added copyright notice to the `ctl` and `voice` modules 

## Type of change

Bug fix + Code cleanup.

## How Has This Been Tested?

Manually tested all changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-11-19 15:17 UTC, psanders commented
@efraa I recommend you review this by commit. Not need to review d4ff536d04fc14485823bbec2651b02fa93f1657 since it a linting commit.

2022-11-21 14:50 UTC, efraa requested changes, later dismissed

2022-11-21 14:50 UTC, efraa commented on docs/reference/VoiceResponse.md
> +  await response.say("Hello workd");   // Plays the sound using GoogleTTS's default values
```suggestion
  await response.say("Hello world"); // Plays the sound using GoogleTTS's default values
```

2022-11-21 14:50 UTC, efraa commented on docs/reference/VoiceResponse.md
> +| options.source | <code>string</code> | Where to listen as input source. This option accepts `dtmf` and `speech`. A speech provider must be configure when including the `speech` source. You might in
```suggestion
| options.source | <code>string</code> | Where to listen as input source. This option accepts `dtmf` and `speech`. A speech provider must be configure when including the `speech` source. You might include both with `dtmf,speech`. Defaults to `dtmf` |
```

2022-11-21 14:50 UTC, efraa commented on docs/reference/VoiceResponse.md
> +must run the anwer command.
```suggestion
must run the answer command.
```

2022-11-22 17:17 UTC, merged