Feat: TTS provider plugin check cache before synthesizing
fonoster/fonoster pull request #448
Opened 2022-11-28 05:29 UTC by xquanluu

2022-11-28 05:30 UTC, xquanluu commented
Hi @psanders  I created here a small draft version of #333, please help to check and give comment. thanks

2022-11-29 23:01 UTC, psanders commented on mods/tts/src/plugin.ts
> +import { SynthResult, TTSConfig, TTSPlugin } from "./types";
Could you add the copyright notice to this file? Feel free to add a note including your contribution.

2022-11-29 23:04 UTC, psanders requested changes
All changes seem great to me.

2022-11-29 23:07 UTC, psanders commented on mods/marytts/src/types.ts
>  /*
Would you move the copyright notice to the very top?

2022-11-29 23:09 UTC, psanders commented
@efraa since this touches a full feature I would also like to have your review. Everything looks great to me, so I want to focus in making sure it doesn't introduce any breaking changes.

2022-11-30 03:35 UTC, xquanluu commented
Thanks @psanders  I fixed your comments.

2022-12-15 10:39 UTC, efraa approved these changes

2022-12-15 10:40 UTC, efraa commented
LGTM!

2022-12-15 17:47 UTC, psanders approved these changes

2022-12-15 17:47 UTC, merged

2022-12-15 17:48 UTC, psanders commented
@xquanluu thanks again for this amazing collaboration 🙌