Feat: Add ProgressIndicator Component
fonoster/fonoster pull request #681
Opened 2024-12-21 21:01 UTC by obrucheoghene

## Description

Create the ProgressIndicator component #676

![Screenshot 2024-12-21 at 9 59 27 PM](https://github.com/user-attachments/assets/ce1d6043-8ba2-467d-8d1d-d330022a34fc)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Implement different stories  for the storybook

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-12-21 22:27 UTC, psanders commented on mods/webui/src/stories/progessindicator/ProgressIndicator.styles.ts
> +export const StyledProgressContainer = styled("div")(({ theme }) => ({
The theme is unused.

2024-12-21 22:27 UTC, psanders commented on mods/webui/src/stories/progessindicator/ProgressIndicator.styles.ts
> +export const StyledIndicatorLabelList = styled("ol")(({ theme }) => ({
The theme is unused.

2024-12-21 22:27 UTC, psanders commented on mods/webui/src/stories/progessindicator/ProgressIndicator.styles.ts
> +export const StyledIndicatorLabel = styled("li")(({ theme }) => ({}));
The theme is unused.

2024-12-21 22:30 UTC, psanders commented on mods/webui/src/stories/progessindicator/ProgressIndicator.tsx
> +            <Typography variant="body-small">{step}</Typography>
Can you take another pass at the styles? The remaining steps appear unhighlighted (for lack of a better term).

<img width="657" alt="Screenshot 2024-12-21 at 5 22 13 PM" src="https://github.com/user-attachments/assets/ea5b79a9-b19c-43a2-95a5-8dc10543cda5" />

2024-12-21 22:30 UTC, psanders requested changes
This looks super smooth! I added a comment to review the styles.

2024-12-21 23:21 UTC, obrucheoghene commented
Unused theme removed.
Thank you

2024-12-21 23:28 UTC, psanders commented on mods/webui/src/stories/progessindicator/ProgressIndicator.tsx
> +            <Typography variant="body-small">{step}</Typography>
@obrucheoghene, this portion still needs addressing.

2024-12-22 00:59 UTC, obrucheoghene commented on mods/webui/src/stories/progessindicator/ProgressIndicator.tsx
> +            <Typography variant="body-small">{step}</Typography>
fixed.

2024-12-22 02:10 UTC, merged

2024-12-22 02:11 UTC, psanders commented
@obrucheoghene 

All set here! Fantastic work, my friend.

2024-12-22 06:40 UTC, obrucheoghene commented
@psanders 
Thanks.